import { Center, Container, Stack } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container py={16} h="60vh">
          <Center h="full">
            <Stack>
              <Link
                href={
                  "/posts/How-to-run-a-IoTeX-Full-Node-on-a-Raspberry-Pi-Board"
                }
              >
                Post1: How to run a IoTeX Full Node on a Raspberry Pi Board
              </Link>
              <Link href={"/posts/Blockchain-Powered-Smart-Lock"}>
                Post2: A Blockchain Powered Smart-Lock with Arduino Nano IoT 33
              </Link>
            </Stack>
          </Center>
        </Container>
      </main>
    </div>
  );
};

export default Home;
